#!/usr/bin/env bash
#
# Remove what setup.sh generated. Nothing outside linux-local-cmweb/ is touched.
#
#   ./clean.sh           remove site/, stubs symlink, var/, repository/, cache/
#   ./clean.sh --all     also remove ENV/ and the database
#
# Every path removed here is regenerated by ./setup.sh.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

ALL=0
case "${1:-}" in
    --all)      ALL=1 ;;
    -h|--help)  sed -n '3,9p' "${BASH_SOURCE[0]}"; exit 0 ;;
    '')         ;;
    *)          echo "Unknown option: $1" >&2; exit 2 ;;
esac

# site/apps and stubs point outside this folder. rm -rf on a symlink removes
# the link rather than the target, but remove them explicitly first so that a
# future change to the layout cannot turn this into a recursive delete of
# cmweb-app.
for link in "$HERE/site/apps" "$HERE/stubs"; do
    if [ -L "$link" ]; then
        rm -f "$link"
    fi
done

rm -rf "$HERE/site" "$HERE/var" "$HERE/repository" "$HERE/cache" \
       "$HERE/static" "$HERE/test-results"
echo "removed: site/ var/ repository/ cache/ static/ test-results/ stubs"

if [ "$ALL" -eq 1 ]; then
    rm -rf "$HERE/ENV"
    rm -f "$HERE/cm_web_db"
    echo "removed: ENV/ cm_web_db"
fi
